# Generated by Django 5.2 on 2025-04-14 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="bookmark",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
